import { test, expect } from '@playwright/test'
import { environment, start, define } from './helpers.mjs'
import { scripted, stats } from './fixtures.mjs'
import { mkdir } from 'node:fs/promises'

test('model-defined dual plugin: review, trust, tools, panel, stop, reconnect, restore', async ({ page, context }) => {
  const env = await environment()
  let server = await start(env)
  try {
    await define(server, 'default', scripted)
    await page.goto(`${server.url}/#token=${server.token}`)
    await expect(page.getByRole('heading', { name: '今天想一起完成什么？' })).toBeVisible()
    await expect(page.getByRole('complementary', { name: '会话导航' })).toBeVisible()
    await expect(page.locator('.sidebar-session').filter({ hasText: 'default' })).toBeVisible()
    await expect(page.getByRole('textbox', { name: '消息', exact: true })).toBeEnabled()
    await expect(page.getByRole('alert')).toHaveCount(0)
    await mkdir('../output/playwright', { recursive: true })
    await page.screenshot({ path: '../output/playwright/morrow-restored-home.png', fullPage: true, animations: 'disabled' })
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('define stats')
    await page.getByRole('button', { name: '发送', exact: true }).click()
    await expect(page.getByText('Completed.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: '插件', exact: true }).click()
    const card = page.locator('article.plugin').filter({ has: page.getByRole('heading', { name: stats.name, exact: true }) })
    await card.getByText('审阅 Host / Client 源码与依赖锁', { exact: true }).click()
    await expect(card.getByRole('heading', { name: 'Host', exact: true })).toBeVisible()
    await card.getByRole('button', { name: '信任此版本' }).click()
    await card.getByRole('button', { name: '激活', exact: true }).click()
    await expect(card.getByText('已绑定', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: '返回工作区', exact: true }).click()
    await page.getByRole('button', { name: '查看会话面板', exact: true }).click()
    await expect(page.getByTestId('project-stats')).toContainText('等待运行')
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('run stats')
    await page.getByRole('button', { name: '发送', exact: true }).click()
    await expect(page.getByTestId('project-stats')).toHaveText('1 files · 1 lines · 1 runs')
    await expect(page.getByRole('button', { name: '停止执行', exact: true })).toHaveCount(0)
    await context.setOffline(true)
    await context.setOffline(false)
    await expect(page.getByTestId('project-stats')).toHaveText('1 files · 1 lines · 1 runs')
    await mkdir('../output/playwright', { recursive: true })
    await expect(page.getByRole('alert')).toHaveCount(0)
    await page.screenshot({ path: '../output/playwright/morrow-restored-chat.png', fullPage: true, animations: 'disabled' })
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: '插件', exact: true }).click()
    await card.getByRole('button', { name: '停用', exact: true }).click()
    await page.getByRole('button', { name: '返回工作区', exact: true }).click()
    await expect(page.getByTestId('project-stats')).toHaveCount(0)
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('button', { name: '插件', exact: true }).click()
    await card.getByRole('button', { name: '激活', exact: true }).click()
    await server.stop()
    server = await start(env)
    await page.goto(`${server.url}/#token=${server.token}`)
    await expect(page.getByTestId('project-stats')).toHaveCount(0)
    await page.getByRole('button', { name: '查看会话面板', exact: true }).click()
    await page.getByRole('button', { name: '加载已信任面板', exact: true }).click()
    await expect(page.getByTestId('project-stats')).toHaveText('1 files · 1 lines · 1 runs')
    await page.getByRole('button', { name: '事实时间线', exact: true }).click()
    await page.getByText(/request_prepared/).first().click()
    await page.getByRole('button', { name: '重建模型请求', exact: true }).first().click()
    await expect(page.getByTestId('reconstructed-request')).toContainText('"input"')
    await expect(page.getByTestId('reconstructed-request')).toContainText('"plan"')
  } finally { await server.stop(); await env.dispose() }
})

test('client renderer failure leaves committed host state available', async ({ page }) => {
  const env = await environment(), server = await start(env)
  try {
    await define(server, 'default', scripted)
    await define(server, 'default', { ...stats, client: "export default ctx => {ctx.ui.panel('Broken', () => {throw new Error('renderer failure')})}" })
    await page.goto(`${server.url}/#token=${server.token}`)
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('run stats')
    await page.getByRole('button', { name: '发送', exact: true }).click()
    await page.getByRole('button', { name: '查看会话面板', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('renderer failure')
    await expect(page.getByText('Completed.', { exact: true })).toBeVisible()
    expect((await server.state('default')).plugin_state[stats.name].stats.runs).toBe(1)
  } finally { await server.stop(); await env.dispose() }
})
