// Generated by cargo run --bin export-types. Do not edit.

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type ToolCall = { id: string, name: string, arguments: JsonValue, };

export type Role = "system" | "user" | "assistant" | "tool";

export type Message = { role: Role, content: string, reasoning: string, tool_calls: Array<ToolCall>, tool_call_id: string | null, };

export type ToolDefinition = { name: string, description: string, parameters: JsonValue, approval: boolean, };

export type Registration = { kind: string, name: string, plugin: string, version: string, scope: string, epoch: string, generation: number, tool: ToolDefinition | null, };

export type RequestHeader = { profile?: string, provider: string, model: string, system: string, tools: Array<ToolDefinition>, parameters: JsonValue, };

export type PreparedRequest = { id: string, run: string, step: string, purpose: string, revision: number, surface: Array<string>, temporary: Array<Message>, header: RequestHeader, registrations: Array<Registration>, plan: PreparedPlan | null, retry_of: string | null, };

export type PreparedPlan = { format: string, payload: JsonValue, profile?: JsonValue, };

export type Continuation = { provider: string, format: string, data: JsonValue, };

export type ModelInput = { header: RequestHeader, messages: Array<Message>, continuations: Array<Continuation | null>, };

export type ModelResult = { message: Message, continuation: Continuation | null, usage: JsonValue, finish_reason: string, };

export type ModelError = { code: string, message: string, details: JsonValue, };

export type Outcome = "completed" | "failed" | "cancelled" | "not_started" | "unknown";

export type PluginManifest = { name: string, description: string, host: string, client: string | null, 
/**
 * Locked, bundled dependencies: no install scripts execute during activation.
 */
dependency_lock: string, };

export type PluginVersion = { hash: string, manifest: PluginManifest, };

export type Fact = { "type": "session_imported", source: string, seq: number, hash: string, nodes: { [key in string]?: Node }, surface: Array<string>, } | { "type": "session_opened", workspace: string, parent: string | null, } | { "type": "input_queued", submission: string, message: Message, } | { "type": "run_started", run: string, submission: string, epoch: string, } | { "type": "step_started", run: string, step: string, registrations: Array<Registration>, } | { "type": "step_ended", step: string, } | { "type": "model_requested", request: PreparedRequest, } | { "type": "request_prepared", request: PreparedRequest, } | { "type": "effect_started", id: string, run: string, step: string, kind: string, name: string, input: JsonValue, } | { "type": "effect_settled", id: string, outcome: Outcome, output: JsonValue, } | { "type": "model_settled", request: string, result: ModelResult | null, error: ModelError | null, } | { "type": "tool_settled", call: string, message: Message, } | { "type": "approval_requested", id: string, run: string, name: string, input: JsonValue, } | { "type": "approval_decided", id: string, approved: boolean, } | { "type": "context_appended", id: string, message: Message, } | { "type": "surface_replaced", revision: number, start: string, end: string, id: string, message: Message, covers: Array<string>, source_request: string | null, } | { "type": "run_ended", run: string, outcome: Outcome, reason: string, } | { "type": "plugin_defined", version: PluginVersion, } | { "type": "plugin_trusted", hash: string, } | { "type": "plugin_bound", name: string, hash: string, active: boolean, } | { "type": "plugin_state_set", namespace: string, key: string, value: JsonValue, } | { "type": "plugin_state_deleted", namespace: string, key: string, } | { "type": "plugin_event", namespace: string, version: number, name: string, data: JsonValue, };

export type Record = { protocol: number, seq: number, previous: string, fact: Fact, hash: string, };

export type Node = { message: Message, continuation: Continuation | null, covers: Array<string>, };

export type Run = { id: string, submission: string, epoch: string, };

export type Step = { id: string, registrations: Array<Registration>, };

export type Effect = { run: string, step: string, kind: string, name: string, input: JsonValue, outcome: Outcome | null, output: JsonValue, };

export type Approval = { run: string, name: string, input: JsonValue, approved: boolean | null, };

export type Binding = { hash: string, active: boolean, };

export type Projection = { legacy: boolean, seq: number, workspace: string, parent: string | null, revision: number, nodes: { [key: string]: Node }, surface: Array<string>, inputs: { [key: string]: Message }, claimed: Array<string>, run_ids: Array<string>, step_ids: Array<string>, run: Run | null, step: Step | null, requests: { [key: string]: PreparedRequest }, settled_requests: Array<string>, effects: { [key: string]: Effect }, pending_tools: Array<string>, tool_results: { [key: string]: string }, approvals: { [key: string]: Approval }, plugins: { [key: string]: PluginVersion }, trusted: Array<string>, bindings: { [key: string]: Binding }, plugin_state: { [namespace: string]: { [key: string]: JsonValue } }, last_outcome: Outcome | null, };

